# Alias
alias ls='lsd'
alias la='lsd -a'
alias ll='lsd -l'
alias vimrc='vim ~/.vimrc'
alias zshrc='vim ~/.zshrc'
alias reboot='doas systemctl reboot'
alias shutdown='doas systemctl poweroff'
alias tree='lsd --tree'
alias grep='grep --color'
