" Vim Config

" Basic settings
set number
set incsearch
set hlsearch
set smartcase
set ignorecase
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set encoding=utf-8
set showcmd
set clipboard=unnamedplus
set cursorline
set ruler

filetype on
filetype plugin indent on
syntax on

" Key binds
let mapleader="<Alt>"
"nnoremap <Leader>
nnoremap <A-Left>  :bprevious<CR>
nnoremap <A-Right> :bnext<CR>
nnoremap <A-Up>    :bfirst<CR>
nnoremap <A-Down>  :blast<CR>

" Plugs
call plug#begin('~/.vim/plugged')

Plug 'nordtheme/vim'
Plug 'rust-lang/rust.vim'
Plug 'frazrepo/vim-rainbow'
Plug 'jiangmiao/auto-pairs'
Plug 'dense-analysis/ale'
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'

call plug#end()

" Color
colorscheme nord
let g:rainbow_active=1

" lightline
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'nord',
      \ 'active': {
      \     'left': [
      \         [ 'mode', 'paste' ],
      \         [ 'gitbranch' ,'readonly', 'filename', 'modified' ]
      \     ],
      \     'right': [
      \         [ 'lineinfo' ], [ 'percent' ],
      \         [ 'fileformat', 'fileencoding', 'filetype' ]
      \     ]
      \ }
      \ }

" ALE
let g:ale_enabled = 1
let g:ale_completion_enabled = 1
let g:ale_set_balloons = 1
let g:ale_completion_autoimport = 1
let g:ale_linters = {
      \ 'rust': ['analyzer'],
      \ 'c': ['clangd'],
      \ 'cpp': ['clangd']
      \ }
let g:ale_c_clangd_executable = '/usr/bin/clangd'
let g:ale_cpp_clangd_executable = '/usr/bin/clangd'
let g:ale_rust_analyzer_executable = '/usr/bin/rust-analyzer'
let g:ale_sign_error = '!'
let g:ale_sign_warning = '>'
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
set omnifunc=ale#completion#OmniFunc
autocmd FileType c,cpp,rust setlocal completeopt=menu,menuone,noselect
autocmd FileType c,cpp,rust inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"

augroup fmt
    autocmd!
    autocmd BufWritePre *.cpp,*.cc,*.c,*.h,*.hpp silent! execute ':!clang-format -i %'
    autocmd BufWritePre *.cpp,*.cc,*.c,*.h,*.hpp silent! edit!
augroup END

set wildmenu
set showmatch
set background=dark
