bar:
  location: top
  height: 30
  font: "JetBrainsMono Nerd Font:size=14"
  foreground: eceff4ff
  background: 2e3440ff

  right:
    - alsa:
        card: "default"
        mixer: "Master"
        content:
          map:
            conditions:
              online:
                map:
                  on-click: /bin/sh -c "amixer -q sset Master toggle"
                  conditions:
                    muted: {string: {text: "󰝟"}}
                    ~muted:
                      ramp:
                        tag: percent
                        items: 
                          - string: {text: "󰕿 {percent}%"}
                          - string: {text: "󰖀 {percent}%"}
                          - string: {text: "󰕾 {percent}%"}
    - network:
        name: enp1s0
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default: {string: {text: "󰱟 "}}
                  conditions:
                    state == up && ipv4 != "": {string: {text: "󰩠 "}}

    - clock:
        time-format: "%H:%M"
        content:
          string:
            text: "󰥔 {time}"
            deco:
              background: 
                color: b48eadff

