#!/bin/sh
# River autostart

# Wallpaers
pgrep -f 'swww-daemon -f argb -l background -q' || riverctl spawn "swww-daemon -f argb -l background -q && swww img ${HOME}/Picture/nord/wild.png"

#pgrep -f 'waydroid session start' || riverctl spawn "waydroid session start"

#riverctl spawn "waydroid session start"

