#!/bin/sh
# River Config

. $HOME/.scripts/color.sh
. $HOME/.config/river/autostart
. $HOME/.config/river/bindings

# Input
riverctl set-repeat 25 260

riverctl xcursor-theme Adwaita 18
riverctl hide-cursor when-typing enabled
riverctl allow-tearing enabled
riverctl focus-follows-cursor normal

riverctl keyboard-layout us

# Border & Color
riverctl background-color 0x${nord0}
riverctl border-color-focused 0x${nord8}
riverctl border-color-unfocused 0x${nord3}
riverctl border-color-urgent 0x${nord11}
riverctl border-width 3

# Window rules
riverctl rule-add -app-id "*" ssd
riverctl rule-add -app-id "QQ" float
riverctl rule-add -app-id "WonderLab" float
riverctl rule-add -app-id "Mindustry" fullscreen
riverctl rule-add -app-id "electron" -title "Open Folder" float

# Layout mgr
if command -v filtile > /dev/null 2>&1; then
    riverctl default-layout filtile
    pgrep -f 'filtile' || riverctl spawn "${HOME}/.scripts/filtile_configed.sh"
    rivercarro -per-tag -no-smart-gaps -inner-gaps 0 -outer-gaps 0 -main-ratio 0.50 &
else
    riverctl default-layout rivertile
    pgrep -f 'rivertile' || riverctl spawn "rivertile -view-padding 5 -outer-padding 5 -main-location left -main-count 1 -main-ratio 0.58"
fi

systemctl --user import-environment {,WAYLAND_}DISPLAY; systemctl --user start river-session.target

