#!/bin/sh

geometry=$(slurp)

if [ -z "$geometry" ]; then
    echo "Selection canceled, exiting." >&2
    exit 1
fi

sleep 0.1

grim -g "$geometry" - | wl-copy && notify-send -u low "$(basename $0)" "Screenshot taken at $(date +'%Y%m%d%H%M')"

