# Path
PATH="$PATH:/home/fts427/.local/bin"
export PATH="$PATH:/home/fts427/.dotnet/tools"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=999999999
SAVEHIST=999999999

# Beep
setopt beep
bindkey -e
zstyle :compinstall filename '/home/fts427/.zshrc'

# Repo
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Alias
alias ls='lsd'
alias la='lsd -a'
alias ll='lsd -l'
alias vimrc='vim ~/.vimrc'
alias zshrc='vim ~/.zshrc'
alias reboot='doas reboot'
alias shutdown='doas shutdown now'
alias showip='ip addr|grep -i "enp0s25"'
alias unxz='tar -xf'
alias untgz='tar -zxvf'
alias dfg='df --block-size=GB'

# Key Map
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
# rxvt
bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix

# Rust
fpath+=~/.zfunc

# PiPy
__pip() {
compadd $( COMP_WORDS="$words[*]" \
COMP_CWORD=$((CURRENT-1)) \
PIP_AUTO_COMPLETE=1 $words[1] 2>/dev/null )
}
if [[ $zsh_eval_context[-1] == loadautofunc ]]; then
__pip "$@"
#else
#compdef __pip -P 'pip[0-9.]#'
fi

# Git
autoload -Uz compinit && compinit
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%b'

# Prompt
PROMPT='%B%F{cyan}[%n]%f@%F{blue}[%m]%F{green}[%1~]%f%b> '
RPROMPT='%B%F{yellow}['\$vcs_info_msg_0_']%f%F{white}[%*][%D]%f%b'

# C Cache
export USE_CCACHE=1
export CCACHE_SLOPPINESS=file_macro,include_file_mtime,time_macros
export CCACHE_UMASK=002
export CCACHE_DIR=/var/tmp/ccache


