
[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor]
blink_interval = 550
vi_mode_style = { shape = "Block", blinking = "Never" }

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBriansMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
opacity = 0.9

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 2
y = 2
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "ArrowUp", mods = "Control|Shift", action = "ScrollPageUp" },
   { key = "ArrowDown", mods = "Control|Shift", action = "ScrollPageDown"},
   { key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown"},
   { key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp"},
   { key = "Home", mods = "Control|Shift", action = "ScrollToTop"},
   { key = "End", mods = "Control|Shift", action = "ScrollToBottom"},
   { key = "S", mods = "Control|Shift", action = "SearchForward"}
]

[general]
live_config_reload = true
